In [ ]:
%pip install scikit-learn pandas openpyxl

In [38]:
from typing import Iterator
import pandas as pd
import sklearn.cluster
from IPython.display import display

def subsets_by_cluster(df: pd.DataFrame) -> Iterator[pd.DataFrame]:
    db = sklearn.cluster.DBSCAN(min_samples=3)
    db.fit(df.notnull())
    df["subset"] = db.labels_

    for _, subset in df.groupby("subset"):
        not_empty_columns = subset.dropna(how="all", axis="columns").columns
        yield subset[not_empty_columns]

cities = pd.read_excel("cities.xlsx").set_index("City")
display(cities)
for subset in subsets_by_cluster(cities):
    display(subset)

,Country,PopulationDensity,Area (sq km),Population,Elevation (m),YearFounded,Mayor,Climate,MajorIndustry
City,,,,,,,,,
Tokyo,Japan,6382,2194.0,14000000.0,40.0,1603.0,NaN,NaN,NaN
Delhi,India,12800,1484.0,19000000.0,200.0,1639.0,NaN,NaN,NaN
Shanghai,China,3785,6340.0,24000000.0,4.0,1291.0,NaN,NaN,NaN
São Paulo,Brazil,7889,1521.0,12000000.0,760.0,1554.0,NaN,NaN,NaN
Mexico City,Mexico,6060,1485.0,9000000.0,2240.0,1325.0,NaN,NaN,NaN
Cairo,Egypt,3241,3085.0,10000000.0,23.0,969.0,NaN,NaN,NaN
Mumbai,India,20725,603.0,12500000.0,14.0,1507.0,NaN,NaN,NaN
Beijing,China,1310,16410.0,21500000.0,43.0,1045.0,NaN,NaN,NaN
Dhaka,Bangladesh,29085,306.0,8900000.0,4.0,1608.0,NaN,NaN,NaN
Osaka,Japan,12000,225.0,2700000.0,20.0,1496.0,NaN,NaN,NaN
Seoul,South Korea,15987,NaN,NaN,NaN,NaN,Oh Se-hoon,Humid continental,Technology & Electronics
Bangkok,Thailand,5300,NaN,NaN,NaN,NaN,Chadchart Sittipunt,Tropical savanna,Tourism & Trade
Paris,France,21000,NaN,NaN,NaN,NaN,Anne Hidalgo,Oceanic,Luxury Goods & Tourism
Cairo,Egypt,10500,NaN,NaN,NaN,NaN,Ahmed Ghanim,Desert,Construction & Media
Istanbul,Turkey,2900,NaN,NaN,NaN,NaN,Ekrem İmamoğlu,Mediterranean,Manufacturing & Logistics
Moscow,Russia,4900,NaN,NaN,NaN,NaN,Sergey Sobyanin,Humid continental,Energy & Finance
Lagos,Nigeria,18000,NaN,NaN,NaN,NaN,Babajide Sanwo-Olu,Tropical savanna,Oil & Port

,Country,PopulationDensity,Area (sq km),Population,Elevation (m),YearFounded,subset
City,,,,,,,
Tokyo,Japan,6382,2194.0,14000000.0,40.0,1603.0,0
Delhi,India,12800,1484.0,19000000.0,200.0,1639.0,0
Shanghai,China,3785,6340.0,24000000.0,4.0,1291.0,0
São Paulo,Brazil,7889,1521.0,12000000.0,760.0,1554.0,0
Mexico City,Mexico,6060,1485.0,9000000.0,2240.0,1325.0,0
Cairo,Egypt,3241,3085.0,10000000.0,23.0,969.0,0
Mumbai,India,20725,603.0,12500000.0,14.0,1507.0,0
Beijing,China,1310,16410.0,21500000.0,43.0,1045.0,0
Dhaka,Bangladesh,29085,306.0,8900000.0,4.0,1608.0,0
Osaka,Japan,12000,225.0,2700000.0,20.0,1496.0,0

,Country,PopulationDensity,Mayor,Climate,MajorIndustry,subset
City,,,,,,
Seoul,South Korea,15987,Oh Se-hoon,Humid continental,Technology & Electronics,1
Bangkok,Thailand,5300,Chadchart Sittipunt,Tropical savanna,Tourism & Trade,1
Paris,France,21000,Anne Hidalgo,Oceanic,Luxury Goods & Tourism,1
Cairo,Egypt,10500,Ahmed Ghanim,Desert,Construction & Media,1
Istanbul,Turkey,2900,Ekrem İmamoğlu,Mediterranean,Manufacturing & Logistics,1
Moscow,Russia,4900,Sergey Sobyanin,Humid continental,Energy & Finance,1
Lagos,Nigeria,18000,Babajide Sanwo-Olu,Tropical savanna,Oil & Port,1